### ISSUE TITLE
Add support for automated Changelog creation

### ISSUE THREAD

**Issue by robinbowes** [segmentio/terraform-docs#102]
### Prerequisites

- [ x ] This issue describes a feature request.

### Description

Would you be able to create and maintain a CHANGELOG showing what has changed in each new release?

**Comment by metmajer** [comment]
Hi @robinbowes and thank you for your interest in this project. We maintain a list of changes with our [releases](https://github.com/segmentio/terraform-docs/releases). Hope this works for you?

**Comment by robinbowes** [comment]
That's perfect - maybe link to that from the README.md so it's more obvious?

**Comment by khos2ow** [comment]
I kinda like having a CHANGELOG, and by convention we can keep updating it per PR and eventually at release time copy/paste its content to release note. Specially that it can have an `unreleased` section at the very top (all the time) that immediately gives feedback _what_ will be released next.

**Comment by metmajer** [comment]
Seems like the overview under [releases](https://github.com/segmentio/terraform-docs/releases) is good enough and I don't see too much sense in maintaining the same information in two different places. What's planned can be seen [here](https://github.com/segmentio/terraform-docs/issues). @robinbowes Does the current solution with [releases](https://github.com/segmentio/terraform-docs/releases) work for you for now? In the near future, we may consider automatically creating a CHANGELOG from the commit messages, but I don't give this too much priority at the moment.

**Comment by robinbowes** [comment]
My preference would be a CHANGELOG, for the reasons @khos2ow states.

The overview under releases is the next best thing, if it's linked to from the README.

**Comment by metmajer** [comment]
I guess we could use something similar to https://github.com/github-tools/github-release-notes to automatically generate a CHANGELOG file in the near future.

**Comment by metmajer** [comment]
Just to be clear, this above-mentioned tool not the best choice, since we'd need to introduce a NodeJS dependency into our build process.

**Comment by metmajer** [comment]
Done in #104. Results can be seen in [CHANGELOG.md](CHANGELOG.md).

**Comment by robinbowes** [comment]
Fantastic work. Thanks!
