### ISSUE TITLE
heredoc not terminated

### ISSUE THREAD

**Issue by beatcracker** [segmentio/terraform-docs#105]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug.
- [ ] This issue describes a feature request.

### Description

Using configuration below, I get `2019/02/07 18:48:52 At 4:2: heredoc not terminated` error

```hcl
locals {
  no_newline = <<EOF
foobarEOF
}
```

The source is `hcl` library:

- [scanner.go#L417](https://github.com/segmentio/terraform-docs/blob/master/vendor/github.com/hashicorp/hcl/hcl/scanner/scanner.go#L417)
- [scanner.go#L468](https://github.com/segmentio/terraform-docs/blob/master/vendor/github.com/hashicorp/hcl/hcl/scanner/scanner.go#L468)

I'm using terraform `v0.11.11` and it's able to parse this configuration.

### Version

`0.6.0`

**Comment by metmajer** [comment]
Hi @beatcracker and apologies for the late reply. Would you want to take a stab at it?

**Comment by metmajer** [comment]
@beatcracker ping

**Comment by beatcracker** [comment]
Here I am... Totally forgot about that, sorry. Thing is, this is looks like an error in the `hcl` vendor module and I'm not sure how to go about fixing that. Raise an issue in [hashicorp/hcl](https://github.com/hashicorp/hcl)?

**Comment by metmajer** [comment]
Thanks for the update. If you can identify this as a bug in the legacy HCL, an issue would be good to have. Would you create that?

**Comment by seboudry** [comment]
Hi!
Same issue on Terraform 0.12.6 and latest terraform-docs (icommit 737bc8d).

Have tested some workarounds without any success:
* using `+` as string concatenation (as https://github.com/hashicorp/hcl/issues/211#issuecomment-330080196)
```
Error: Invalid expression
Expected the start of an expression, but found an invalid expression token.
```
* using `<<-EOM`

So I'll switch back to monoline string.

**Comment by khos2ow** [comment]
@seboudry would you please share the config you used to reproduce the issue? I'll try to see what I can find out.

**Comment by gopisaba** [comment]
I am still seeing this problem in terraform 0.12.10

terraform code
```hcl
variable "test_list" {
  default     = []
  type        = list(any)
  description = <<-EOF
    Description
  EOF
}
```
error message:
```
Terraform docs...........................................................Failed
hookid: terraform_docs

2019/11/17 21:09:12 At 53:1: heredoc not terminated
```

**Comment by tbugfinder** [comment]
Which version of the hook repo are you using?

**Comment by gopisaba** [comment]
```yaml
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.19.0
  hooks:
    - id: terraform_fmt
    - id: terraform_docs
```

**Comment by khos2ow** [comment]
I've just tested this issue with various commits (ab42f0d097d5246a446ad5ca450c2073c6a30bdc, ec346a0fe8f8fc97e628908aa22d12525059a636, 737bc8dc18d0fca385d99a34b95e43b325e1fdf9) and with following two sample datas
```
variable "test_list" {
  default     = []
  type        = "list"
  description = <<-EOF
    Description and something
    even multiline
  EOF
}
```
and
```
variable "test_list" {
  default     = []
  type        = "list"
  description = <<EOF
    Description and something
    even multiline
EOF
}
```
and in all cases the documents were generated successfully. There's one thing I wanted to point out that if you're using `<<-` as the prefix the indentation of `EOF` must exactly under `description` otherwise you'd get the `heredoc not terminated` issue.

I'd like to ask you folks to may be double check your configs and please report back if this is still a relevant issues (if so, please share the exact config you have problem with), otherwise I'd like to close this issue.

**Comment by gopisaba** [comment]
Yes, it works if you default set with heredoc description. 
Try with no default value set, something like

```hcl
variable "test_list" {
  type        = "list"
  description = <<-EOF
    Description and something
    even multiline
  EOF
}
```
```hcl
variable "test_list" {
  type        = "list"
  description = <<EOF
    Description and something
    even multiline
EOF
}
```

**Comment by khos2ow** [comment]
Thanks for the quick feedback, I just tried your snippets for both `markdown document` and `markdown table`, and they still work.
Can you try with `HEAD` of master to see if we can still see this?

**Comment by gopisaba** [comment]
yay!!! it works from master branch. Thanks @khos2ow

**Comment by khos2ow** [comment]
Awesome! I'm gonna close this issue then, please let me know if you still experience this issue.
