### ISSUE TITLE
feature request: structured 'examples' section

### ISSUE THREAD

**Issue by tedder** [segmentio/terraform-docs#106]
### Prerequisites
- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

### Description
When building documentation for a module (where, generally, the only HCL files are limited and in the root dir), it'd be nice to have some form of structured 'examples' section. I'm currently putting them in a comment header at the top of main.tf, which causes it to get generated into the docs, but it'd be nice if thy could come from `examples/` or somewhere like that. For instance, this file structure:

```
  examples/hello.tf
  examples/minimal.tf
```

Might result in the following being added just below the header of the generated docs:
```
## examples
### hello
(contents of hello.tf, automagically indented for markdown)
### minimal
(contents of minimal, automagically indented for markdown)
```

**Comment by metmajer** [comment]
Hi @tedder! Apologies for the late reply. I understand where you're coming from, but I don't think that processing examples should be a scope of the project. What holds you back from either including examples directly in your `README.md`, or using a tool like `sed` to load your examples into it?

**Comment by tedder** [comment]
What holds me back is that this generates a markdown file, so I use it to generate my README.md in one step. That's okay though, putting it in a carefully structured comment works for us.

**Comment by metmajer** [comment]
`terraform-docs` does not create a markdown file per se. We do create markdown content that you can write into your file, at least that's how most of our users do it. Cheers!
