### ISSUE TITLE
Support comments like jsdoc style

### ISSUE THREAD

**Issue by hendrixroa** [segmentio/terraform-docs#109]
### Description

I opened an issue on `terraform` repository about generate documents from comments like jsdoc style (https://github.com/hashicorp/terraform/issues/21135). 

Is it this project support for ?

**Comment by metmajer** [comment]
Hi @hendrixroa! I've been able to observe in the ticket above that you already found a solution. Anyways, we do already support document generation from comments, albeit not from jsdoc. I am not sure if jsdoc is widely accepted in the Terraform space, at least I haven't made that observation yet. Want to share your perspective?

**Comment by hendrixroa** [comment]
My perspective was generating documentation from inline comments, but for not reinvent the wheel I used this https://github.com/Gufran/terraform-docs to generate markdown docs from comments.
