### ISSUE TITLE
restore and remove the annoying bask slashs

### ISSUE THREAD

**Issue by ozbillwang** [segmentio/terraform-docs#111]
### Prerequisites

Put an `x` into the box that applies:

- [x ] This issue describes a bug.
- [ x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

With old version, we get normal variable names properly. But from new version (not sure from which release), the variable name has annoying back slashs, can we remove them?

#### Actual Behavior

Briefly describe what happened.

```
aws\_default\_region
```

Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

Briefly describe what you expected to happen.

```
aws_default_region
```

### Replication Case

Tell us which steps to take to replicate your problem.

1. ...
2. ...
3. ...

### Version

You can get this information via `terraform-docs --version`.

**Comment by ozbillwang** [comment]
Go through the history, seems it related to release 0.0.5

#48 
#63 

I still don't understand why in markdown name `aws_region` is a bug and need be fixed with ugly `aws\_region`?

**Comment by sjauld** [comment]
Underscores denote italics, and hence should be escaped. I guess support for a -no-escape-underscores flag would make sense.

**Comment by ozbillwang** [comment]
Thanks, @sjauld 

I tested with github, bitubucket, I didn't see the letter shows as italics. Which we are mostly using these tools.

**Comment by ozbillwang** [comment]
Test with https://johnmacfarlane.net/babelmark2/?text=%7C+Name+%7C+Description+%7C+Type+%7C+Default+%7C+Required+%7C%0A%7C------%7C-------------%7C%3A----%3A%7C%3A-----%3A%7C%3A-----%3A%7C%0A%7C+input%5C_with%5C_underscores+%7C+A+variable+with+underscores.+%7C+string+%7C+n%2Fa+%7C+yes+%7C%0A%7C+input_with_underscores+%7C+A+variable+with+underscores.+%7C+string+%7C+n%2Fa+%7C+yes+%7C

Click `preview`

In markdown `table`, it doesn't change the letters to italics.

**Comment by sjauld** [comment]
Quite a few of the examples on that page are italicised (RedCarpet, Pandoc
etc)

**Comment by jufemaiz** [comment]
Original spec says you’ll need to either escape the character. Ref: https://daringfireball.net/projects/markdown/syntax#em

That being said, given its a variable it should be treated as inline code and single back ticked.

**Comment by sjauld** [comment]
It kills me to say this, but yet again @jufemaiz has a good point.

**Comment by jufemaiz** [comment]
I'd probably also inline-code style the `type` and the `default` value to emphasise that they are values and not comments.

**Comment by metmajer** [comment]
Hey @ozbillwang and thanks for your contribution. #62 has absolute precedence and I won't make any changes to the project before we have a solution on that one. Unfortunately, my schedule is crazy at the moment, so thanks for your patience.

**Comment by metmajer** [comment]
@jufemaiz back in 0.5.0, we made the decision to not use inline-code style for names, types, default values since, while syntactically being correct, would be distracting and decrease readability. How do you think about this @jufemaiz @khos2ow @ozbillwang @sjauld?

**Comment by sjauld** [comment]
My preference would be to follow the specification and use backticks. I almost always view readmes via a rendering engine; backticks would improve the appearance of the document. 

IMHO, default behaviour should always be as per the specification, with exotic changes to be included via an option if there is really demand for that feature.

**Comment by metmajer** [comment]
@sjauld I understand that you would favour to have name, type and default value to be ``-ed. Which specification are you referring to?

**Comment by sjauld** [comment]
Ah, I was referring to the one posted by @jufemaiz - probably not
technically a specification but probably the closest markdown will come to
one!

**Comment by jufemaiz** [comment]
I would definitely prefer to take on the single backtick inline code method as per Gruber’s original markdown spec as per https://github.com/segmentio/terraform-docs/issues/111#issuecomment-495476227

Not only would it render better when using a markdown to HTML converter but would also be indicative to readers that the text enclosed by the back ticks is indeed code, variable or similar.

**Comment by khos2ow** [comment]
I wanted to point out that currently the default value is already being back ticked. And I'm in favor of escaping special characters (we are doing them - not all yet though - for the description).

Also this issue only happens in `markdown` printer which has two types of `table` and `document`. We are escaping the name and put them in a heading (`###`) and to me it will slightly feel weird if we want to inline code something in one formatter which in the other is not inline coded.

May be we can introduce a new flag `--no-escape`.

**Comment by ozbillwang** [comment]
I vote to add a new flag `--no-escape`. It can resolve the pain for both sides.

**Comment by metmajer** [comment]
`--no-escape` sounds a little broad to me as some characters need to be escaped in order to render proper Markdown, whereas others are more for layout. Not sure about this myself, yet, but I suggest something more concrete in the naming. Thoughts?

**Comment by jufemaiz** [comment]
How about `--md-relaxed` for non-markdown-ed-but-markdown-esque output?

**Comment by khos2ow** [comment]
I personally like `--no-escape` better because we already have two other similar flags: `--no-sort` and `--no-required`. And also note that with current usage of `docopt` we cannot have such flag as `--something=true|false`, but if we proceed with #116 and move to Cobra then we would have this ability. Then we can have the following (or even considering new flags or deprecating old ones in `v1.0.0`):

- `--sort=false|true|required|name|value|...`
- `--escape=true|false`

**Comment by jufemaiz** [comment]
I'd advocate defaulting `--no-escape` to `false` though (i.e. no-escape by exception rather).

**Comment by khos2ow** [comment]
Yes I agree, if we go forward with negative `--no-foo` flags, they should default to false.

**Comment by metmajer** [comment]
@khos2ow I planned to do this anyway, but I'll reopen your Cobra PR #116 and have it merged this week. Seriously, isn't `--no-escape` or even `--no-markdown-escape` too broad? We still want to escape `|`, `_`, right? Assuming this is correct, we need a better name.

**Comment by metmajer** [comment]
Let's do it the following way. Since `|` and `_` have to be escaped to be valid Markdown, a `--no-markdown-escape` should be sufficient. @khos2ow since I have just merged #166, we should be able to avoid being repetitive in the flag name and just say `--no-escape`, right?

**Comment by khos2ow** [comment]
@metmajer yes, I believe `--no-escape` is sufficient because it's gonna only be tied to `markdown` subcommand, so the `markdown` in the name of the flag is already implied.

**Comment by metmajer** [comment]
Ok, great! One more suggestion on the flag to be less general and ambiguous: —no-escape-values. Thoughts? You decide and let’s move on to a PR 👌

**Comment by khos2ow** [comment]
Hmm, I think `--no-escape-values` might be misleading. Values (as in the default value of a variable) will always be rendered in back tick or code block and never need to be escaped. The issue here is the special characters in "name" of the variables. I'm still thinking for an alternative naming of this flag.

**Comment by khos2ow** [comment]
Just opened a PR for this, I've used `--no-escape` as an interim flag name, if we actually came up with an alternative name that can easily be changed only on [this line](https://github.com/segmentio/terraform-docs/pull/117/files#diff-ff7686b39bf90dc2520886fb874371a4R44), the rest of the PR should be good I guess.
