### ISSUE TITLE
Support here document syntax

### ISSUE THREAD

**Issue by ncs-alane** [segmentio/terraform-docs#12]
As mentioned in the [Configuration Syntax](https://www.terraform.io/docs/configuration/syntax.html#_lt_lt_EOT) documentation, multiline strings can be formatted using here document syntax, but as of v0.0.2, variable descriptions using here document syntax are rendered as blank values.

*input*

```hcl
variable "foo" {
  description = <<EOD
This is foo's description.
EOD

  default = "bar"
```

*expected output*

```sh
var.foo ("bar")
This is foo's description
```

*actual output*

```sh
var.foo ("bar")
-

**Comment by yields** [comment]
A PR for this would be appreciated, however i don't really use them, so not a huge deal for me :)

**Comment by ncs-alane** [comment]
I will defer to some one that knows Go. :open_hands:
