### ISSUE TITLE
0.12 support?

### ISSUE THREAD

**Issue by rosscdh** [segmentio/terraform-docs#121]
### Prerequisites

1. install terraform 0.12 
2. have a variable of type `bool`

Put an `x` into the box that applies:

- [x ] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Cant generate docs for variables of type bool

#### Actual Behavior

boolean type variable

```
[14:04:40] ross:harness git:(master*) $ terraform-docs markdown document  .
2019/08/30 14:05:52 At 3:17: Unknown token: 3:17 IDENT bool

[14:05:52] ross:harness git:(master*) $ terraform-docs markdown document  .
2019/08/30 14:07:01 At 2:27: Unknown token: 2:27 IDENT formatdate
```

Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

docs get generated

```
```

### Replication Case

Tell us which steps to take to replicate your problem.

1. install terraform 0.12 
2. have a variable of type `bool`

### Version

You can get this information via `terraform-docs --version`.

0.6.0

**Comment by florianrusch** [comment]
@rosscdh There is already an issue for this: https://github.com/segmentio/terraform-docs/issues/62
