### ISSUE TITLE
Possible to cut a new release?

### ISSUE THREAD

**Issue by amaltson** [segmentio/terraform-docs#122]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Would it be at all possible to cut a new release? With nice features like #117, I'd love to stop using a forked version 😄.

P.S. I removed the rest of the template because it's not relevant for this request. Thanks again!

**Comment by khos2ow** [comment]
I'm going to cut a release today and so I'm closing this issue now.
