### ISSUE TITLE
Underscores escaped incorrectly in default column

### ISSUE THREAD

**Issue by mwarkentin** [segmentio/terraform-docs#145]
### Prerequisites

- [x] This issue describes a bug.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

When generating a markdown doc, underscores in the default value appear to be escaped in the output because it's wrapped in a codeblock. Underscores should not be escaped in the default.

#### Actual Behavior

Example terraform:

```hcl
variable "build_compute_type" {
  description = "The CodeBuild instance type to use. Defaults to 'BUILD_GENERAL1_SMALL'."
  default     = "BUILD_GENERAL1_SMALL"
}
```

Output:

```
## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:-----:|
| build\_compute\_type | The CodeBuild instance type to use. Defaults to 'BUILD\_GENERAL1\_SMALL'. | `string` | `"BUILD\_GENERAL1\_SMALL"` | no |
```

Screenshot:

![](https://s3.amazonaws.com/mwarkentin-snaps/waveaccountingterraform-aws-codepipeline-serverless_AWS_delivery_pipeline_for_Serverless_Framework_applications_2020-01-06_11-21-40.jpg)

#### Expected Behavior

Default value should not include escape characters (`\`):

```
## Inputs

| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:-----:|
| build\_compute\_type | The CodeBuild instance type to use. Defaults to 'BUILD\_GENERAL1\_SMALL'. | `string` | `"BUILD_GENERAL1_SMALL"` | no |
```

### Replication Case

Tell us which steps to take to replicate your problem.

1. Create a module variable with a default value which includes underscores
2. Generate docs

### Version

```
❯ terraform-docs --version
terraform-docs version v0.8.0-alpha darwin/amd64 BuildDate: 2020-01-06T11:28:49-05:00
```

**Comment by khos2ow** [comment]
Thanks @mwarkentin for the feedback, I was able to reproduce this, I'll open a fix PR soon.
