### ISSUE TITLE
Terraform Docs Support of Terraform Lists

### ISSUE THREAD

**Issue by pantocrator27** [segmentio/terraform-docs#15]
As of Terraform 0.7.0, terraform supports lists in variable declarations that does not appear to be supported in Terraform Docs.

**Comment by pvdvreede** [comment]
I just ran into this problem as well where a list type that has a default as `[]` does not register as an optional variable.

**Comment by metmajer** [comment]
@pantocrator27 @pvdvreede Inputs of type `list` are supported by `terraform-docs` for a while. Now, also their default values can be rendered when using the `---with-aggregate-type-defaults` option with #53.
