### ISSUE TITLE
json output - keys capitalized case vs. lowercase (v.0.8.0-rc1)

### ISSUE THREAD

**Issue by tbugfinder** [segmentio/terraform-docs#153]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a question.
- [ ] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

With version v0.8.0-rc1 keys in the json output have lower case format for e.g. Inputs, Outputs, Type, Description, ff. Was this changed intentionally?

https://github.com/segmentio/terraform-docs/blob/a6193849c44c5f2e1b06fabd39994797a9d7527f/internal/pkg/tfconf/module.go#L15-L21

#### Actual Behavior

Json code created with terraform-docs v0.8.0-rc1 has lowercase keys of e.g. inputs and outputs instead of capitalized case. Depending on postprocessing of the json file, this is a breaking change.

```
 terraform-aws-vpc]$ ../terraform-docs-v0.6.0-linux-amd64 --with-aggregate-type-defaults json . |more
{
  "Comment": "",
  "Inputs": [
    {



terraform-aws-vpc]$ ../terraform-docs-v0.7.0-linux-amd64 --with-aggregate-type-defaults json . |more
{
  "Comment": "",
  "Inputs": [
    {
      "Name": "amazon_side_asn",



terraform-aws-vpc]$ ../terraform-docs-v0.8.0-rc.1-linux-amd64 --with-aggregate-type-defaults json . |more
{
  "inputs": [
    {
      "name": "amazon_side_asn",
      "type": "string",


```

Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

Briefly describe what you expected to happen.

```
Json keys should be capitalized letter as with previous versions.
```

### Replication Case

Tell us which steps to take to replicate your problem.

1. clone terraform-aws-vpc module
2. terraform-docs-v0.6.0 json
3. terraform-docs-v0.7.0 json
4. terraform-docs-v0.8.0-rc1 json
5. compare above json output

### Version

You can get this information via `terraform-docs --version`.

v0.6.0, v0.7.0, **v0.8.0-rc1**

**Comment by khos2ow** [comment]
There's no universal guideline for naming convention of JSON property names. [Ecma International](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) section 6 indicates:

> An object structure is represented as a pair of curly bracket tokens surrounding zero or more name/value pairs. A name is a `string`.  ..... The JSON syntax does not impose any restrictions on
the `strings` used as names ...

The most common agreed upon format is `camelCase` (e.g. [google JSON Style Guide](https://google.github.io/styleguide/jsoncstyleguide.xml?showone=Property_Name_Format#Property_Name_Format)), which by convention starts with `lowercase` character.

This was the reason we've decided to change from `CamelCase` to `camelCase` and release `v0.8.0` seemed to be the right time to do the move since we're already introducing couple of soft breaking changes.

**Comment by metmajer** [comment]
@khos2ow I think it would be beneficial to keep the names in JSON as they have been defined in the Terraform config. This allows users to, e.g., create a HTML form, or similar, that is a 1:1 representation of the config. I strongly suggest we recreate this behavior so our users can keep building tools on top of terraform-docs.

**Comment by khos2ow** [comment]
@metmajer I should note that everything extracted from user's Terraform config is being kept as is, and used literally as they are, but the name of properties in JSON structure have been lowercased:

```json
{
  "Inputs": [
    {
      "Name": "Whatever-User-Provider",
      "Type": "string"
    },
    ...
  ]
}
```

 have been changed to:

```json
{
  "inputs": [
    {
      "name": "Whatever-User-Provider",
      "type": "string"
    },
    ...
  ]
}
```

To be fair, this is a breaking change which I'll be adding it to changelog, but I believe this is the right time to bite the bullet on this.

**Comment by metmajer** [comment]
Agreed. I just thought we should be clear which keys in the JSON result have been changed and which did not get touched 👍

**Comment by tbugfinder** [comment]
Thanks for clarification - so it's by intention.

**Comment by khos2ow** [comment]
Updated breaking change section of current [unreleased](https://github.com/segmentio/terraform-docs/blob/master/CHANGELOG.md#unreleased) changelog regarding the renaming of JSON properties.

Closing this issue.

**Comment by tbugfinder** [comment]
Hi @khos2ow,
as shown above also the lower keys (name, type) within e.g. Inputs changed to lower-case.

**Comment by khos2ow** [comment]
Sorry for the confusion on my part, what I meant https://github.com/segmentio/terraform-docs/issues/153#issuecomment-573125995 , specifically

> This was the reason we've decided to change from CamelCase to camelCase and release v0.8.0 seemed to be the right time to do the move since we're already introducing couple of soft breaking changes.

and https://github.com/segmentio/terraform-docs/issues/153#issuecomment-573205995

> I should note that everything extracted from user's Terraform config is being kept as is, and used literally as they are, but the name of properties in JSON structure have been lowercased

Conversion of properties name to lowercase is universal throughout the JSON format output. I hope that clarifies this.
