### ISSUE TITLE
Error unknown token with 0.8.0-rc2

### ISSUE THREAD

**Issue by smutel** [segmentio/terraform-docs#156]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

When I am generating the documentation with command `terraform-docs md .`, the error message below is displayed:

```
2020/01/13 11:50:13 At 6:35: Unknown token: 6:35 IDENT split
```

#### Actual Behavior

Briefly describe what happened.

```
Error message, the documentation is not generated.
```

#### Expected Behavior

Briefly describe what you expected to happen.

```
No error message and documentation generated.
```

### Replication Case

Tell us which steps to take to replicate your problem.

1. Create a terraform code main.tf with:
```hcl
locals {                                                                        
  ip_suffix_list                = split(",", var.ip_suffixes)                   
  nb_instances                  = var.ip_suffixes == "" ? 0 : length(local.ip_suffix_list)
  region_list                   = split(",", var.regions)                       
  zone_list                     = split(",", var.zones)
  ...
}
```
2. Start `terraform-docs md .` 

### Version

`terraform-docs version dev linux/amd64 BuildDate: 2020-01-13T11:51:21+01:00 (v0.8.0-rc.2)`

**Comment by khos2ow** [comment]
I wasn't able to reproduce this. How did you run the `terraform-docs` command? Did you download the binary from release page or did you build it from the source?

Can you make sure to download the latest binary from [release page](https://github.com/segmentio/terraform-docs/releases/tag/v0.8.0-rc.2) or make sure you pull down the current `HEAD` of master and try again?

**Comment by khos2ow** [comment]
Actually I did a little bit of digging and this error can be reproduced from immediate commit before b8da8c5 and prior. So at this point I'm pretty sure you don't have recent codes pulled down from the HEAD of master.

**Comment by smutel** [comment]
I am using the 0.8.0-rc2 from release page.

**Comment by smutel** [comment]
Arf ... multiple terraform-docs in multiple binary folders (go/bin and /usr/local/bin). Sorry.
