### ISSUE TITLE
v0.8.0-rc2 only accepts a path instead of files compared to previous versions

### ISSUE THREAD

**Issue by tbugfinder** [segmentio/terraform-docs#157]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug or is a question about the changelog.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description
Previous versions of terraform-docs accepted files as an input. Version 0.8.0-rc2 only accepts a PATH argument for processing.
I couldn't find this as a planned change.

#### Actual Behavior

I'm running a pre-commit hook which would only process variables.tf. This fails with an error in terraform-docs 0.8.0-rc2.
I'd like only to get inputs (variables) within the json file.
```
$ terraform-docs version
terraform-docs version v0.8.0-rc.2 d52122d linux/amd64 BuildDate: 2020-01-12T20:38:24+0000
$
$ terraform-docs --no-sort --with-aggregate-type-defaults json variables.tf
2020/01/13 22:53:30 Failed to read module directory: Module directory variables.tf does not exist or cannot be read.
```

Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

Either it should be documented in the Changelog (i might have missed it though) or it should still process variables.tf as a file instead of a folder.

### Replication Case

Tell us which steps to take to replicate your problem.

1. Create terraform file myvariables.tf
```
variable "id" {
  description = "id"
  type        = "string"
}

variable "name" {
  description = "name"
  type        = "string"
}

variable "tags" {
  default     = {}
  description = "tags"
  type        = "map"
}

```
Execute previous terraform command:
```
$ terraform-docs.v0.6.0 json myvariables.tf
{
  "Comment": "",
  "Inputs": [
    {
      "Name": "id",
      "Description": "A unique identifier.",
      "Default": null,
      "Type": "string"
    },
    {
      "Name": "name",
      "Description": "The name of the blueprint.",
      "Default": null,
      "Type": "string"
    },
    {
      "Name": "tags",
      "Description": "A map of tag key-value pairs.",
      "Default": {
        "Type": "map",
        "Value": {}
      },
      "Type": "map"
    }
  ],
  "Outputs": null
}

```
1. Execute `terraform-docs variables.tf` 
```
$ terraform-docs json  myvariables.tf
2020/01/13 22:59:49 Failed to read module directory: Module directory myvariables.tf does not exist or cannot be read.
```
### Version

You can get this information via `terraform-docs --version`.
$ terraform-docs version
terraform-docs version v0.8.0-rc.2 d52122d linux/amd64 BuildDate: 2020-01-12T20:38:24+0000

**Comment by metmajer** [comment]
@tbugfinder the support for files has been dropped a while ago. `terraform-docs` creates documents for one Terraform module at a given path. Hope this clarifies!

**Comment by tbugfinder** [comment]
Then, I'd like to ask to add this to the Changelog for terraform v0.8.0.

Thanks.

**Comment by khos2ow** [comment]
I completely forgot we had been supporting file as an input parameters! I'll try to see if we can add it back with minimal effort otherwise I'll definitely add it to the changelog.
