### ISSUE TITLE
v0.8.0-rc2 -- json output doesn't add null defaults

### ISSUE THREAD

**Issue by tbugfinder** [segmentio/terraform-docs#158]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

v0.8.0-rc2 doesn't set defaults for all `Inputs`. 

#### Actual Behavior
If no default value for a variable is set, the json output doesn't have a default key:value of `default:null`.

```
$ terraform-docs --with-aggregate-type-defaults json /tmp/terraform-docs/
{
  "header": "",
  "inputs": [
    {
      "name": "name",
      "type": "string",
      "description": "name"
    },
    {
      "name": "namewithdefault",
      "type": "string",
      "description": "name",
      "default": "\"this is a default value\""
    },
    {
      "name": "tags",
      "type": "map",
      "description": "tags",
      "default": "{}"
    }
  ],
  "outputs": [],
  "providers": []
}
$
$
$ terraform-docs  json /tmp/terraform-docs/
{
  "header": "",
  "inputs": [
    {
      "name": "name",
      "type": "string",
      "description": "name"
    },
    {
      "name": "namewithdefault",
      "type": "string",
      "description": "name",
      "default": "\"this is a default value\""
    },
    {
      "name": "tags",
      "type": "map",
      "description": "tags",
      "default": "{}"
    }
  ],
  "outputs": [],
  "providers": []
}

```

Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

Each `input` should have a key default as in previous versions (e.g. v0.6.0). If there's no default set in *.tf files then the default value should be `null` .

```
$ terraform-docs.v0.6.0 --with-aggregate-type-defaults json /tmp/terraform-docs/variables.tf
{
  "Comment": "",
  "Inputs": [
    {
      "Name": "name",
      "Description": "name",
      "Default": null,
      "Type": "string"
    },
    {
      "Name": "namewithdefault",
      "Description": "name",
      "Default": {
        "Type": "string",
        "Value": "this is a default value"
      },
      "Type": "string"
    },
    {
      "Name": "tags",
      "Description": "tags",
      "Default": {
        "Type": "map",
        "Value": {}
      },
      "Type": "map"
    }
  ],
  "Outputs": null
}

```

### Replication Case

Tell us which steps to take to replicate your problem.

1.  terraform-docs --with-aggregate-type-defaults json /tmp/terraform-docs/

### Version

You can get this information via `terraform-docs --version`.
$ terraform-docs --version
terraform-docs version v0.8.0-rc.2 d52122d linux/amd64 BuildDate: 2020-01-12T20:38:24+0000

**Comment by khos2ow** [comment]
Thanks for reporting, I'll open the PR now.
