### ISSUE TITLE
Generate Section for requirements

### ISSUE THREAD

**Issue by smutel** [segmentio/terraform-docs#159]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

### Description

It will be great to parse this kind of terraform code:

```hcl
terraform {
  required_version = ">= 0.12"
}
```

And to generate the table below in the documentation:

```md
## Requirements

| Name | Version |
|------|---------|
| terraform | >= 0.12 |
```

**Comment by tbugfinder** [comment]
IMHO, this is close to or an extension to feature #140 (listing providers).
Could the table include the requirement as well as the actual version used? Note that the provider version could also be locked using above code like:
```
terraform {
  required_version = ">= 0.12"
  required_providers {
    aws = "~> 2.40"
  }
}
```

This is terraform 0.12 feature though.

**Comment by khos2ow** [comment]
That's a great suggestion @smutel but I'm a little bit hesitant to include this in `v0.8.0` as we're already in RC2. I'm gonna plan this for the upcoming `v0.9.0` release.

**Comment by VR6Pete** [comment]
Thanks for this - is this on track for 0.9.0? Cheers. Pete

**Comment by khos2ow** [comment]
@VR6Pete It is in plan for `v0.9.0` but I haven't started on it yet.

**Comment by khos2ow** [comment]
Hey folks, to start on this again, I'm completely in favor of having a `Requirements` section or some sort to show the minimum required terraform binary for the module to work, but I'm not entirely sure (at the moment) about the table format. The reason is that it's always gonna have only one row, and why not showing it as list item rather than a full blown table?

```
## Requirements

- Terraform >= 12.0
```

instead of:

```
## Requirements

| Name | Version |
|------|---------|
| terraform | >= 0.12 |
```

What are your thoughts on this?

> Could the table include the requirement as well as the actual version used? Note that the provider version could also be locked using above code

@tbugfinder also I didn't get your point here, may be at the time of your comment it was lacking, but now if you explicitly have defined `required_providers` block it will show them in the `Providers` table.

**Comment by tbugfinder** [comment]
Hi @khos2ow ,
might thought was showing additional info of the version requirement like `>=0.12`. So also include the actual used version like `0.12.20`. Or e.g. if the aws provider requirement is >=2.40 then `terraform init`  might install version `2.52`. Therefore this rather a post-execution request than an overall documentation feature.

**Comment by khos2ow** [comment]
That might be a little bit hard to do, as there's no indication of the version of in use terraform or the providers at runtime. The only place I can think of is the state which we cannot access to get those information to populate in the README. I'm gonna explore more but at the moment I cannot think of anything else.

**Comment by smutel** [comment]
@tbugfinder, the idea here is to display in the README the minimum terraform requirements to be able to use a module.  
It the requirement is a terraform version upper to 0.12, we don't care if terraform version 0.12.10 or version 0.12.20 will be used ...
If you are sure that your module will not work with terraform 0.12.20, then use `required_version = "= 0.12.10"` for example.

**Comment by tbugfinder** [comment]
@smutel I got the idea of the requirements section and like it. I just wanted to bring in my thought that it could also make sense to output used versions compared to required constraints also. I see this like a post-deployment documentation comparable to document output values. I don't want to delay your issue, though.

**Comment by khos2ow** [comment]
Both are valid arguments as a Terraform _module_ both refer to the set of config which will solely used by others, and also the set of config which you actually created the infrastructure with. The exact version of binary or providers used will only make sense in the latter (the same for recently added output values functionality).

I think in the scope of this issue we need to agree on the cosmetic representation of the required Terraform binary (show as list, or table or etc) and track the possibility of extracting the actual version being used in another issue (although I still don't know how we would be able to do that)

**Comment by tbugfinder** [comment]
My personal preference is the table as it's more consistent with inputs and outputs.

**Comment by khos2ow** [comment]
@smutel @tbugfinder @VR6Pete can you take a look at #222 and give any potential feedback you have? I've combined both 1) terraform and 2) providers required version together in the same list. The provider(s) is a little bit redundant of the ones in `Providers` section but I figured that'd be ok because this, at the end of the day, is a _requirement_.

**Comment by VR6Pete** [comment]
Looks good to me!
