### ISSUE TITLE
Inject `terraform output` into `terraform-docs` as an additional 'Value' field 

### ISSUE THREAD

**Issue by gshel** [segmentio/terraform-docs#165]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

### Description
I'd like to have `terraform-docs` add an optional field for Outputs which would specify the current value of an output variable as it's found in state via `terraform output`.

My use-case:
The outputs of my Terraform project get imported into the Terraform projects of my users as variables. Ideally, my documentation would inform users what value to expect when they use them.

Let me know if any of that could use further clarification or if you have any feedback or suggestions.

Cheers!

**Comment by khos2ow** [comment]
Thank you for the suggestion, this might be very hard to implement (if possible at all), I'm gonna plan this to think about in the next release.

**Comment by gshel** [comment]
I'm still a bit new to go, but I'd be happy to lend a hand. I have teammates who put together a similar feature in a [fork](https://github.com/coveord/terraform-docs) of the previous version of terraform-docs. The flags relating to it are `--no-sensitive` and `--out-values`

**Comment by khos2ow** [comment]
That's great, let me know if you want to give it a try yourself, otherwise I'll circle back to this later on in `v0.9.0` after I took care of other issues/features particularly  #149.

**Comment by gshel** [comment]
I think I will give it a go - _pun intended_. To better understand what's going on in the code, do you have any suggestions as to which module/file/class I should look at first?

**Comment by khos2ow** [comment]
Awesome! First of all I suggest that this feature should be an opt-in approach, so a new flag required (for example `--output-values true|false` default to `false). This opt-in approach will be needed to

1) be backward compatible
2) and more importantly not all modules can or will have output values at rest, it means they are meant to be used _somewhere_ else which at that point any outputs defined will have value

The interesting files to start looking at are:

- `internal/pkg/tfconf/output.go`
- `internal/pkg/tfconf/module.go`
- to extract values may be a new type of _reader_ in `internal/pkg/reader/` (or may be all private functions inside `internal/pkg/tfconf/output.go`. TBD)

Please don't hesitate to reach out if you have any questions or concerns.

**Comment by gshel** [comment]
@khos2ow I have 60% of the PR done already, although at the moment:

1. my flag accepts a string instead of a bool
    - If I change the flag to a bool, users:
        - won't be able to specify which file contains their outputs
        - will be forced to use whatever filename we dictate

An alternative that comes to mind would be to use environment variables. What do you think of that?

2. I don't yet have tests written up, any preferences for those?

**Comment by khos2ow** [comment]
Hmm I'm not sure at the moment, I suggest then to open a draft PR, as is, l for me to be able to see the code.
