### ISSUE TITLE
Line break in heredoc is not honoured

### ISSUE THREAD

**Issue by melcloud** [segmentio/terraform-docs#167]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description
String in terraform heredoc requires extra line break to render properly in markdown

#### Actual Behavior

Given follow variable, I expect the description to be formatted as shown in markdown. However, no line break is rendered between *image:* and *uid:*

pretty version works as expected

```
variable "envoy_config" {
  description = <<-EOT
    Configuration for Envoy proxy container

    image:            The image tag in ECR for appmesh envoy. Default to aws-appmesh-envoy:v1.12.1.1-prod
    uid:              The user identifier used to run container under a specific user. Default to 1337
    ingress_port:     The port used by envoy to accept inbound traffic. Any requests to the contianer port will be redirected to this
    egress_port:      The port used by envoy for outbound traffic. Any outboud traffic will be redirected to this
    log_level:        The log level of envy. Default to info
    egress_ignore_ip: The egress traffic going to the specified IP addresses is ignored and not redirected to envoy_egress_port
  EOT
  type        = object({ image = string, uid = string, ingress_port = number, egress_port = number, log_level = string, egress_ignore_ip = list(string) })
  default = {
    image            = "aws-appmesh-envoy:v1.12.1.1-prod",
    uid              = "1337",
    ingress_port     = 15000,
    egress_port      = 15001,
    log_level        = "error",
    egress_ignore_ip = ["169.254.170.2", "169.254.169.254"]
  }
}
```

Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

Render new lines as it is in heredoc for markdown

```
```

### Replication Case

Tell us which steps to take to replicate your problem.

1. Define above variable in variables.tf
2. Run terraform-docs markdown .

### Version
terraform-docs version v0.8.0-rc.3 1d33e9d darwin/amd64 BuildDate: 2020-01-16T22:09:49+0000

**Comment by khos2ow** [comment]
If you look at the raw generated of markdown you'd see the multi-lines paragraph is there (same as `pretty`) but that's how Markdown renders them. I'm gonna add `<space><space>` (double space) at the end of multi-lines paragraph which will produce single line-break (effectively `\n`)
