### ISSUE TITLE
feature request: include inline docs in markdown output

### ISSUE THREAD

**Issue by ketzacoatl** [segmentio/terraform-docs#17]
I have been using terraform-docs a little bit recently, and I really like it. I am not sure how to address the following desire. I would like to generate docs for my modules which have some explanation and other details before the input/output (API) info the tool currently renders.

With tf-docs as it is now, I would need to combine the output from the tool with a snippet from a doc file, into a new .md that is actually used as the final doc. That would require developer interaction each time the module is updated. I would rather be able to rely on CI tooling to "run tf-docs" to generate the module docs, and I think that would be possible if tf-docs were to support either extracting these types of snippets from the `.tf` files, or having a `.tpl` that is used as a prefix to the existing output from tf-docs. Maybe this is already possible and I Just overlooked it?

Thoughts?

**Comment by yields** [comment]
Glad you found this tool useful.

I think this feature is supported already, if you include a [header doc](https://github.com/segmentio/terraform-docs/blob/master/_example/main.tf#L1-L9) it'll be rendered before the input/output docs, is this what you were looking for?

**Comment by ketzacoatl** [comment]
Yes, that looks perfect. If you would agree and find it useful, I'd like to send in a PR that updates the example in the README  - the screenshot of the stack module suggests this is possible, but I'd like to update the example embedded in the README to make this more obvious. Does that sound reasonable?

**Comment by ketzacoatl** [comment]
Ah! I also found out why my initial tests of the details in the example you linked to failed.. I used `/*` instead of `/**` in starting the header/comment.

**Comment by yields** [comment]
> Yes, that looks perfect. If you would agree and find it useful, I'd like to send in a PR that updates the example in the README - the screenshot of the stack module suggests this is possible, but I'd like to update the example embedded in the README to make this more obvious. Does that sound reasonable?

a better example would be nice! :)

**Comment by ketzacoatl** [comment]
I dropped the ball here, sorry about that. Thanks to @nwalke for picking up that slack!
