### ISSUE TITLE
Variables with default = null are marked as required

### ISSUE THREAD

**Issue by matsest** [segmentio/terraform-docs#176]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug.

### Description

In terraform 0.12.x it is possible to use the `null` [type](https://www.terraform.io/docs/configuration/expressions.html) for variables in cases where you want a [conditionally omitted variable](https://www.hashicorp.com/blog/terraform-0-12-conditional-operator-improvements/):

```

variable "test" {
  description = "example of an optional variable that should be ignored if not assigned"
  default        = null
}
```

This makes for a variable that by default is *NOT* required for terraform, and thus should be marked as *Required: no* in the output from `terraform-docs`.

#### Actual Behavior

Variables with `default = null` are marked as required.

* For json output, variables with `default = null` are treated same as variables without any default value, which are marked as `"default": null`.
* For markdown table output, all variables without `default = null` are marked with Required: yes
* For markdown document output, variables with `default = null` are treated same as variables without any default value, which are not appended any default value information.

#### Expected Behavior

Variables with `default = null` should not be marked as required.

* For json output, variables with `default = null` should be distingushed from variables without any default value.
* For markdown table output, all variables without `default = null` should be marked with Required: no.
* For markdown document output, variables with `default = null` should be marked with `Default: null`.

### Replication Case

Tell us which steps to take to replicate your problem.

1. Add `default = null` to a variable
2. Run `terraform-docs md table .` or `terraform-docs md document .`
3. Examine output

### Version

`terraform-docs version v0.8.0 linux/amd64 BuildDate: 2020-01-21T16:47:59+01:00`

**Comment by matsest** [comment]
See also: https://github.com/hashicorp/terraform-config-inspect/issues/23 and https://github.com/hashicorp/terraform-config-inspect/pull/24 for a similar issue.

**Comment by khos2ow** [comment]
That's an interesting issue. The PR in `terraform-config-inspect` seems to be stalled, I'm gonna wait a bit to see if we can get the functionality directly from there otherwise we have to implement it directly within `terraform-docs`, but.

How would you differentiate between the "empty" and "non-existent" values, in terms of rendering? I can only think of something like this at the moment:

```
Name: some-variable
Default: null <-- doesn't exist

vs

Name: some-variable
Default: `null` <-- explicitly set to 'null' in tf file
```

**Comment by matsest** [comment]
Hm, if this should be solved in the parsing I think it makes sense the expand the Input type to have an `i.isRequired()` function, similar to the one for `terraform-config-inspect`. What do you think?

Then the json output could have the attribute exported (`"Required": yes/no`), the markdown table output could use it for marking yes/no, and for markdown document it could be used to separate between which inputs that are placed in `## Required inputs` and `## Optional inputs`?

**Comment by khos2ow** [comment]
It seems they are not going to proceed with https://github.com/hashicorp/terraform-config-inspect/pull/24, and as such I'm gonna attempt to work around this within this repo. I have a base working fix which I'm gonna open a PR soon (it's kinda hacky though! :man_facepalming:)
