### ISSUE TITLE
Missing newline between inline code and trailing comment in header block

### ISSUE THREAD

**Issue by gdelvalle** [segmentio/terraform-docs#182]
### Prerequisites

Put an `x` into the box that applies:

- [x ] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description
There are missing  newlines  between inline code and trailing comment in the main  header block.  This causes the markdown to render improperly

#### Actual Behavior

If I have a header block in main.tf  comprised of  inline code  and some trailing text,  newlines are removed between the inline code and said text.  This causes  the markdown to render improperly. 

Input Snippet:
in main.tf
```
/**
 * Usage:
 *
 * Example of 'foo_bar' module in `foo_bar.tf`.
 *
 * ```hcl
 * module "foo_bar" {
 *   source = "github.com/foo/bar"
 *
 *   id   = "1234567890"
 *   name = "baz"
 *
 *   zones = ["us-east-1", "us-west-1"]
 *
 *   tags = {
 *     Name         = "baz"
 *     Created-By   = "first.last@email.com"
 *     Date-Created = "20180101"
 *   }
 * }
 * ```
 *
 * Here is some trailing text
 *
 * ##  Header 1
 * More text
 */

resource "tls_private_key" "baz" {}


terraform {
  required_providers {
    aws = ">= 2.15.0"
  }
}

resource "null_resource" "foo" {}
```

Output snippet:
```
Usage:

Example of 'foo\_bar' module in `foo_bar.tf`.

 ```hcl
module "foo_bar" {
  source = "github.com/foo/bar"

  id   = "1234567890"
  name = "baz"

  zones = ["us-east-1", "us-west-1"]

  tags = {
    Name         = "baz"
    Created-By   = "first.last@email.com"
    Date-Created = "20180101"
  }
}
```Here is some trailing text

##  Header 1
More text

## Inputs

No input.

## Outputs

No output.
```
- Note the newlines  between closing  triple backticks and  "Here is some trailing text" are removed"

#### Expected Behavior
Input Snippet:
 Same as above

Output snippet:
```
Usage:

Example of 'foo\_bar' module in `foo_bar.tf`.

\```hcl
module "foo_bar" {
  source = "github.com/foo/bar"

  id   = "1234567890"
  name = "baz"

  zones = ["us-east-1", "us-west-1"]

  tags = {
    Name         = "baz"
    Created-By   = "first.last@email.com"
    Date-Created = "20180101"
  }
}
\```

Here is some trailing text

##  Header 1
More text

## Inputs

No input.

## Outputs

No output.
```
 -  the `\` before the ``` is not in the actual output but added for presentation purposes.  Otherwise github renders the markdown and that might misrepresent what I'm trying to communicate
- note the newlines after the inline code is preserved
- the expected behavior was present in 0.6.0 release

### Replication Case
1.) Save to main.tf
```
/**
 * Usage:
 *
 * Example of 'foo_bar' module in `foo_bar.tf`.
 *
 * ```hcl
 * module "foo_bar" {
 *   source = "github.com/foo/bar"
 *
 *   id   = "1234567890"
 *   name = "baz"
 *
 *   zones = ["us-east-1", "us-west-1"]
 *
 *   tags = {
 *     Name         = "baz"
 *     Created-By   = "first.last@email.com"
 *     Date-Created = "20180101"
 *   }
 * }
 * ```
 *
 * Here is some trailing text
 *
 * ##  Header 1
 * More text
 */

resource "tls_private_key" "baz" {}


terraform {
  required_providers {
    aws = ">= 2.15.0"
  }
}

resource "null_resource" "foo" {}
```
run :
2)terraform-docs markdown . in directory you just saved that main.tf

### Version

terraform-docs version v0.8.1 e7ad477 darwin/amd64 BuildDate: 2020-01-21T15:49:11+0000

**Comment by khos2ow** [comment]
Thank you for reporting the issue, I'll have a PR for this soon.
