### ISSUE TITLE
Unknown token: IDENT lower

### ISSUE THREAD

**Issue by bostrowski13** [segmentio/terraform-docs#202]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Running command produces error "Unknown token: 2:17 IDENT lower"

#### Actual Behavior

Briefly describe what happened.

```
terraform-docs pretty .\my_project\
2020/02/20 09:44:09 At 2:17: Unknown token: 2:17 IDENT lower
```

#### Expected Behavior

A markdown is produced without error.

### Replication Case

Tell us which steps to take to replicate your problem.

1.  Run "terraform-docs pretty .\my_project\

### Version

terraform-docs --version
dev

which is 0.8.2-rc2

Running on windows.

**Comment by khos2ow** [comment]
That version is old and it's RC version, please download the latest stable release from [here](https://github.com/segmentio/terraform-docs/releases) and try it again and update this issue.

**Comment by bostrowski13** [comment]
Hi,

Downloaded the latest release marked 0.8.2 "terraform-docs-v0.8.2-windows-amd64.exe".  Same error.

**Comment by khos2ow** [comment]
Can you share the config file you ran this against and have issue with?

**Comment by bostrowski13** [comment]
i assume its being caused by this...

```
locals {
  bucket_name = lower("${var.resource_prefix}-policy-results")
}
```

**Comment by khos2ow** [comment]
I'm still not able to produce this. I'm gonna try to test this on Windows to see if there was any difference.

**Comment by bostrowski13** [comment]
Thanks for your assistance

**Comment by martinbjorgan** [comment]
Just had some code with the `lower` function in it. Documentation generated as expected with latest code.

**Comment by khos2ow** [comment]
Thank you @martinbjorgan for reporting this, have you tested this on Windows or something else?

**Comment by martinbjorgan** [comment]
@khos2ow tested on windows 👍

**Comment by khos2ow** [comment]
@bostrowski13 do you still have issue with this?

**Comment by bostrowski13** [comment]
I haven't had a chance to come bank to this, and I won't be able to for a while.  sorry for the delay and thanks for your response.

**Comment by bostrowski13** [comment]
so as usual, this is a user problem.  apparently at some point in time i downloaded the code with go get and then later subsequently downloaded the windows binary and put it in another path. 

*facepalm*
