### ISSUE TITLE
directly build terraform.tfvars.json file

### ISSUE THREAD

**Issue by tbugfinder** [segmentio/terraform-docs#206]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

I have the need of creating terraform.tfvars.json file within a project based on projects inputs. While terraform-docs provides loads of json output of all input variables, it doesn't natively provide a limited output useable as terraform.tfvars.json.
Obviously `terraform-docs json` output can be postprocessed using jq (or others). So this is more a convenience request.

#### Actual Behavior

Briefly describe what happened.

```
```

Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

Briefly describe what you expected to happen.
An subcommand of the json option should only create output usable within terraform.tfvars.json file.
```
terraform-docs json . --tfvars-only
```

### Replication Case

Tell us which steps to take to replicate your problem.
N/A

### Version

You can get this information via `terraform-docs --version`.
0.8.2

**Comment by khos2ow** [comment]
Can you provide an example output you expect this to return?

**Comment by tbugfinder** [comment]
The jq command is:
`./terraform-docs-v0.8.2-linux-amd64 json . | jq '.inputs | map({ (.name): .default }) | add'`

Which produces output:  (based on variables.tf of #173)
```
{
  "availability_zone_names": [
    "us-west-1a"
  ],
  "boolwithdefault": true,
  "docker_ports": [
    {
      "external": 8300,
      "internal": 8300,
      "protocol": "tcp"
    }
  ],
  "image_id": null,
  "listwithdefault": [
    "this is elementA",
    "this is elementB",
    "this is elementC"
  ],
  "mapwithdefault": {
    "us-east-1": "image-1234",
    "us-west-2": "image-4567"
  },
  "numberwithdefault": 5,
  "objecttypewithdefaults": {
    "bucket_policy_only": true,
    "lifecycle_rules": {},
    "location": "europe-west4",
    "storage_class": "REGIONAL",
    "versioning_enabled": true
  },
  "stringwithdefault": "this is a default value",
  "tags": {}
}

```

**Comment by tbugfinder** [comment]
Thank you.
Impressive. 👍
