### ISSUE TITLE
List markdown does not appear to work in variable descriptions

### ISSUE THREAD

**Issue by aaronsteers** [segmentio/terraform-docs#215]
### Prerequisites

Put an `x` into the box that applies:

- [X] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Description text in variable declarations is not rendered with support for markdown list items. It looks as though the newline is not carried through and so list items are rendered into concatenated paragraphs.

#### Actual Behavior

The code below demonstrates this issue.

```hcl
variable "input_val" {
  description = <<EOF
Enter one of the following valid inputs:

- Option A
- Option B
- Option C

EOF
  type        = string
  default     = null
}
```

Which renders as:

```md
| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:-----:|
| input\_val | Enter one of the following valid inputs:<br><br>- Option A - Option B - Option C | `string` | n/a | yes |
```

#### Expected Behavior

The result would render correctly if an extra `<br>` were injected before each '-' character - or more simply, as a replacement for any line break in the source. 

Currently it seems the line breaks are only preserved when there are 2 or more breaks in sequence. While this is generally acceptable for paragraphs, the behavior makes structures lists infeasible in this context.

```md
| Name | Description | Type | Default | Required |
|------|-------------|------|---------|:-----:|
| input\_val | Enter one of the following valid inputs:<br><br><br>- Option A <br>- Option B <br>- Option C | `string` | n/a | yes |
```

### Replication Case

Tell us which steps to take to replicate your problem.

(Described above.)

### Version

```
terraform-docs version v0.8.2 e9812fa windows/amd64 BuildDate: 2020-02-03T18:33:59+0000
```

**Comment by khos2ow** [comment]
This should be fixed as part of #208 and will be available in `v0.9.0`. Can you build `HEAD` of master and test your config to validate this?

**Comment by aaronsteers** [comment]
> This should be fixed as part of #208 and will be available in `v0.9.0`. Can you build `HEAD` of master and test your config to validate this?

Unfortunately, I've not yet got a build environment setup and I am afraid I won't have time to run that test. I am happy to wait and retest after v0.9.0 - and can post back here if this is still an outstanding issue.

**Comment by khos2ow** [comment]
Thanks for the update. So I'm gonna close this issue for now and you can test it on a RC release when it comes out and reopen it if you still had issues with it.

**Comment by aaronsteers** [comment]
Sounds good! Thanks, @khos2ow !
