### ISSUE TITLE
[BUG] Inconsistent order in Requirements section

### ISSUE THREAD

**Issue by zopanix** [segmentio/terraform-docs#231]
### Prerequisites

- [x] This issue describes a bug.
- [ ] This issue describes a feature request.

### Description

When running terraform docs, since 0.9.0 we are facing inconsistent output. the order of the requirement sometimes vary. This can cause trouble when CI is validation terraform-docs does not need to perform changes.

#### Actual Behavior

Example of `git diff`

```
 | Name | Version |
 |------|---------|
 | terraform | >= 0.12 |
-| random | >= 2.0.0 |
 | kubernetes | >= 1.10.0 |
+| random | >= 2.0.0 |

```

#### Expected Behavior

I would expect the terraform docs output to be consistent.

### Replication Case

Trying to run terraform-docs several times with multiple requirements.

### Version

```
Terraform v0.12.24
terraform-docs version v0.9.0 89b129b linux/amd64 BuildDate: 2020-03-31T20:19:01+0000
```

**Comment by khos2ow** [comment]
Thank you @zopanix , I was able to reproduce and will have a fix for this soon.

**Comment by zopanix** [comment]
@khos2ow : Thx for the wuick reply
