### ISSUE TITLE
Add support for AsciiDoctor output format

### ISSUE THREAD

**Issue by rdelcampog** [segmentio/terraform-docs#240]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

It would be very useful to have [AsciiDoctor](https://asciidoctor.org/) output format. This language is very simmilar to Markdown so I hope there is no too much work to have it implemented.

**Comment by khos2ow** [comment]
Thank you @rdelcampog for your interest in the project. I've not worked with AsciiDoctor and need to check it out and will put this in the backlog for now, but you are more than welcome if you want to give this a try and send a PR.
The other option is that we're implementing a plug-in system (#149) that user can bring their own _formatter_, in which you can create a custom plug-in for your own use case. Implementing the plug-in system is the main priority of v0.10.0 release at the moment.

**Comment by rdelcampog** [comment]
@khos2ow Hi! I've just send a PR for this renderer based on the Markdown renderer as the syntax is pretty much the same.

Hope you can take a look and is merged soon! Thank you for the good work!
