### ISSUE TITLE
feat: allow header input from a markdown file

### ISSUE THREAD

**Issue by Silthus** [segmentio/terraform-docs#251]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Currently the only way to supply an header (as far as I could find out), is to use a `.tf` file and use the specially crafted comment section `/** ... */`.

#### Actual Behavior

I wanted to use a `header.md` file as my header source. This would give me intellisense and formatting support inside my editor and makes it easier to create nice header documents.

Running: `terraform-docs md . --header-from ./header.md` does not print the header.

#### Expected Behavior

It would be great if a markdown file could be specified to provide the header.

### Version

`terraform-docs version v0.9.1 7f761d3 windows/amd64 BuildDate: 2020-04-02T21:58:38+0000`

**Comment by khos2ow** [comment]
That's a good suggestion and I cannot think of a reason to block this.

**Comment by khos2ow** [comment]
This is added in #252 , besides the original suggestion of supporting `.md` files I added support for reading from `.adoc` and `.txt` files as well.

**Comment by Silthus** [comment]
Wow that was quick. Thanks!
