### ISSUE TITLE
Underscores escaped incorrectly

### ISSUE THREAD

**Issue by wburn-sierra-cedar** [segmentio/terraform-docs#258]
**Describe the bug**

Underscores are escaped in documentation, incorrectly.
```
variable "splunk_logs_config_file_both" {
  type        = string
  description = "splunk logs configuration file"
}
```

```
| splunk\_logs\_config\_file\_path\_s3\_both | splunk logs configuration file | `string` |
```
**To Reproduce**

1.  Create a module variable with a default value which includes underscores
2.   Generate docs

**Expected behavior**

Generate documentation without escaped underscores

**Version information:**

```
terraform-docs --version
terraform-docs version v0.0.0- v0.9.1 darwin/amd64 BuildDate: 2020-04-02T23:00:25+0100
```

**Additional context**

**Comment by khos2ow** [comment]
Can you elaborate a bit more on the issue? This, based on what I understood from your message, is indeed by design. Underscores are being escaped in Markdown and you can explicitly disable them by using `--no-escape` flag.

**Comment by wburn-sierra-cedar** [comment]
hi @khos2ow ,

Thank you so much for your prompt reply.  My apologies for not reading the documentation properly.  You are quite correct, that resolved the issue.  Thank you again.

Cheers,

Will
