### ISSUE TITLE
Output new lines in value not supported

### ISSUE THREAD

**Issue by fatmcgav** [segmentio/terraform-docs#26]
Terraform supports using newlines in output value interpolation, e.g.:
```hcl
output "instance_info" {
  description = "Instance information map, providing instance name and IP address"
  value = "${zipmap(
    openstack_compute_instance_v2.instance.*.name, 
    openstack_networking_port_v2.instance_port.*.all_fixed_ips.0
  )}"
}
```

However this code causes `terraform-docs` to fail with:
> $ terraform-docs md ./outputs.tf
> illegal
> 2017/04/06 09:13:35 At 4:44: illegal char

Putting the `value` on a single line correctly generates docs:
```hcl
output "instance_info" {
  description = "Instance information map, providing instance name and IP address"
  value = "${zipmap(openstack_compute_instance_v2.instance.*.name, openstack_networking_port_v2.instance_port.*.all_fixed_ips.0)}"
}
```
Resulting docs
> ## Outputs
>
>| Name | Description |
>|------|-------------|
>| instance_info | Instance information map, providing instance name and IP address |

**Comment by metmajer** [comment]
@fatmcgav First of all, thank for your interest in this project and for providing the issue report. I am to tell you that this behavior is now supported. A test execution of your example:

```
output "instance_info" {
  description = "Instance information map, providing instance name and IP address"
  value = "${zipmap(
    openstack_compute_instance_v2.instance.*.name, 
    openstack_networking_port_v2.instance_port.*.all_fixed_ips.0
  )}"
}
```

...now correctly yields:

```
## Outputs

| Name | Description |
|------|-------------|
| instance_info | Instance information map, providing instance name and IP address |
```
