### ISSUE TITLE
feature request - modules

### ISSUE THREAD

**Issue by ozbillwang** [segmentio/terraform-docs#33]
I understand this tool is useful to generate README for terraform modules, but I'd like to use it to generate README for any terraform projects, which I found the tool missed the feature to collect the module resources.

Use your example,
 
      module "foo" {
         source = "github.com/foo/baz"
         subnet_ids = "${join(",", subnet.*.id)}"
       }
 

Can we include modules as: 

```
## Modules

| Name | Description | Source | 
|------|-------------|:-----:|
| foo |  | github.com/foo/baz |
```

**Comment by yields** [comment]
I didn't include this because i wanted terraform-docs to document how to use a module, not list them.

Unless i'm misunderstanding this feature is out of scope for this project unfortunately.

**Comment by ozbillwang** [comment]
My response is why not. But it depends on your thought.
