### ISSUE TITLE
Terraform-docs version is incorrect

### ISSUE THREAD

**Issue by eredi93** [segmentio/terraform-docs#37]
when installing 0.2.0 with brew or downloading the binary the version command responds with the incorrect version
```
jacopo@moka:~ ⇒ brew install terraform-docs
==> Downloading https://homebrew.bintray.com/bottles/terraform-docs-0.2.0.sierra.bottle.tar.gz
Already downloaded: /Users/jacopo/Library/Caches/Homebrew/terraform-docs-0.2.0.sierra.bottle.tar.gz
==> Pouring terraform-docs-0.2.0.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/terraform-docs/0.2.0: 6 files, 2.8MB
jacopo@moka:~ ⇒  terraform-docs --version
v0.1.0
```

**Comment by eredi93** [comment]
https://github.com/segmentio/terraform-docs/issues/35 the code got fixed but downloading the release still have that problem. can you replace that release or release a new one?
i use the version command as a version check and i cannot upgrade until this is fixed.
@yields any chance you could do one or the other?

**Comment by eredi93** [comment]
@yields any update?

**Comment by yields** [comment]
Released [v0.3.0](https://github.com/segmentio/terraform-docs/releases/tag/v0.3.0) :)

**Comment by eredi93** [comment]
Thank you!

**Comment by eredi93** [comment]
@yields the brew formula only has the 0.2.0 would be great if you could update that too 😄

**Comment by yields** [comment]
hmm, not sure how to update it, i think it was created by a contributor at (https://github.com/segmentio/terraform-docs/pull/23)

**Comment by eredi93** [comment]
https://github.com/Homebrew/homebrew-core/pull/19728 seems that someone did it already

**Comment by eredi93** [comment]
@yields i just realised that the version is now set to `dev` any particular reason behind that? it makes it hard for me to make sure that the whole team uses the same version 😞

**Comment by yields** [comment]
how did you install it?

the version is set automatically when binaries are built

**Comment by eredi93** [comment]
@yields I installed it with `brew` we may need to change the brew formula. Can you check it?

**Comment by yields** [comment]
gotcha, would it help if i release a new version with the `version` var set properly?
for context, the reason i moved to `dev` is because i don't want to forget to update that variable next time ;)

**Comment by eredi93** [comment]
@yields i created a PR to fix homebrew https://github.com/Homebrew/homebrew-core/pull/19760

**Comment by eredi93** [comment]
my pr got merged 🎉
