### ISSUE TITLE
Feature Request: Markdown: Escape underscores ( _ ) in variables with more than 1 underscore

### ISSUE THREAD

**Issue by kjhosein** [segmentio/terraform-docs#48]
Variable names containing 2 underscores appear with parts of the name italicized in Markdown. 

E.g.:
`three_part_varname`

will look a single word without underscores and the chars 'part' will be italicized. (I can't demonstrate this in the Github comment field.)

**Comment by metmajer** [comment]
Thank you very much for your interest in this project @kjhosein. Are you interesting in making a contribution via a pull request?

**Comment by metmajer** [comment]
Resolved by #63. Thanks, @sjauld and @kjhosein!

**Comment by metmajer** [comment]
@kjhosein see https://github.com/segmentio/terraform-docs/releases/tag/v0.5.0.
