### ISSUE TITLE
New maintainers

### ISSUE THREAD

**Issue by morgante** [segmentio/terraform-docs#54]
@boggsboggs As of 7110697c09f357127900dd48381b29f3fabe863c it looks like Segment is no longer maintaining this project. Are you open to someone else taking over maintenance?

**Comment by metmajer** [comment]
I've also done so some time ago in https://github.com/segmentio/terraform-docs/pull/53. Let's see...

**Comment by metmajer** [comment]
@morgante Thank you for your interest in this project. Lack of maintenance has been resolved with #55. Updates will follow soon.

**Comment by morgante** [comment]
Excellent, thanks for taking this over @metmajer.
