### ISSUE TITLE
example subcommand

### ISSUE THREAD

**Issue by yields** [segmentio/terraform-docs#6]
``` bash
$ terraform-docs example ecs-cluster

module "example" {
  source = "github.com/segmentio/stack/ecs-cluster
  foo       = "baz"
  baz      = "..."
}

```

**Comment by metmajer** [comment]
@yields This issue seems to have become stale and I am unsure about what you're trying to show. Closing for now, but feel free to reopen in case you want to further elaborate on this enhancement.

**Comment by yields** [comment]
oh, the idea was to output an example use of the module, so the defaults will be used.
so instead of you writing the module manually, you would just do this:

```
terraform-docs example ecs-cluster > ./mycluster.tf
```

and then just change the defaults, fill out the required variables and terraform plan -> apply.
