### ISSUE TITLE
Integrate 'gofmt' and 'goimports' into Makefile

### ISSUE THREAD

**Issue by metmajer** [segmentio/terraform-docs#67]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Integrating `gofmt` and `goimports` into the Makefile helps contributors code formatting and package imports automated.

**Comment by metmajer** [comment]
These should be handled through the recent 'golangci-lint` (see #103).

**Comment by khos2ow** [comment]
This issue is covered in #115 with `make fmt` and `make checkfmt` targets.
