### ISSUE TITLE
v0.4.0 release for windows is not recognized as executable

### ISSUE THREAD

**Issue by willegetz** [segmentio/terraform-docs#69]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

The windows 0.4.0 release is not recognized as an executable.

#### Actual Behavior

I downloaded the latest windows release and am unable to run the binary on my windows machine.

#### Expected Behavior

I want to be able to install terraform-docs on my windows machine.

### Replication Case

Tell us which steps to take to replicate your problem.

1. Download 0.4.0 windows release to a windows machine
2. Execution of the download is prohibited

**Comment by metmajer** [comment]
Hi @willegetz. Do you have any error message to share with us? Have you tried running the executable from v0.3.0? Does that one work?

**Comment by metmajer** [comment]
Here's what the Unix `file` command has to say:

```
❯ file ./bin/terraform-docs-v0.4.0-windows-amd64
./bin/terraform-docs-v0.4.0-windows-amd64: PE32+ executable (console) x86-64 (stripped to external PDB), for MS Windows
```

**Comment by willegetz** [comment]
Hi @metmajer, thank you for responding.

After downloading the file and attempting to execute it I see the "How do you want to open this file" promt:
![image](https://user-images.githubusercontent.com/3326805/46374345-5a032a00-c645-11e8-8704-ee006a8f4041.png)
The same prompt is launched when I try and execute the file from PowerShell:
`Start-Process .\terraform-docs-v0.4.0-windows-amd64`

Interestingly enough, when compiling this response, I discovered that when I execute the file from the cmd.exe, I am prompted with the command line parameters:
`> terraform-docs-v0.4.0-windows-amd64`
`    Usage: terraform-docs [--no-required] [--no-sort] [--with-aggregate-type-defaults] [json | markdown | md] <path>...`
`    terraform-docs -h | --help`

Using cmd.exe works to generate terraform docs as described.

Thank you for your time,
William Getz

**Comment by metmajer** [comment]
@willegetz likewise, thanks for the update! Can you please try and see if the executable can be started if you append the `.exe` extension to the filename?

**Comment by X-Guardian** [comment]
@metmajer, yes, I can confirm that the Windows release binary is missing its `.exe` extension and adding this allows the binary to run.

**Comment by metmajer** [comment]
Much appreciated, @X-Guardian!

**Comment by willegetz** [comment]
I apologize for the delay in response @metmajer, and am grateful for @X-Guardian verifying your question.

Thank you both.
