### ISSUE TITLE
Comment Field Blank

### ISSUE THREAD

**Issue by jmcmaster05** [segmentio/terraform-docs#73]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

While trying out the example from the [README.md](https://github.com/segmentio/terraform-docs/blob/master/README.md), the `Comment` field is not getting populated.

> "Comment": "",

#### Actual Behavior

`./terraform-docs-v0.4.0-darwin-amd64 --version`

> 0.4.0

`cat _example`

```terraform
/**
 * This module has a variable and an output.  This text here will be output before any inputs or outputs!
 */

variable "subnet_ids" {
  description = "a comma-separated list of subnet IDs"
}

// The VPC ID.
output "vpc_id" {
  value = "vpc-5c1f55fd"
}
```

`./terraform-docs-v0.4.0-darwin-amd64 json _example`

```json
{
  "Comment": "",
  "Inputs": [
    {
      "Name": "subnet_ids",
      "Description": "a comma-separated list of subnet IDs",
      "Default": null,
      "Type": "string"
    }
  ],
  "Outputs": [
    {
      "Name": "vpc_id",
      "Description": "The VPC ID."
    }
  ]
}
```

#### Expected Behavior

```json
{
  "Comment": "This module has a variable and an output.  This text here will be output before any inputs or outputs!\n",
  "Inputs": [
    {
      "Name": "subnet_ids",
      "Description": "a comma-separated list of subnet IDs",
      "Default": ""
    }
  ],
  "Outputs": [
    {
      "Name": "vpc_id",
      "Description": "The VPC ID.\n"
    }
  ]
}
```
### Version

`./terraform-docs-v0.4.0-darwin-amd64 --version`

> 0.4.0

**Comment by metmajer** [comment]
Hi @jmcmaster05, and thanks for documenting the issue!

Can you please check if the problem is resolved if you...

1) clone the project into your workspace
2) call `make build`
3) call `./bin/terraform-docs-v0.4.0-darwin-amd64 _example`

? Thanks for giving it a try!

**Comment by metmajer** [comment]
@jmcmaster05 I've just released terraform-docs v0.4.5. Please check this update and let me know if the problem persists (which I couldn't replicate on my Mac).

**Comment by jmcmaster05** [comment]
Works! Thanks.

`./terraform-docs-v0.4.5-darwin-amd64 md main.tf`

>     # Module Title
>    
>     This module has a variable and an output.  This text here will be output before any inputs or outputs!
>    
>     ## Inputs
>    
>     | Name | Description | Type | Default | Required |
>     |------|-------------|:----:|:-----:|:-----:|
>     | subnet_ids | a comma-separated list of subnet IDs | string | - | yes |
>    
>     ## Outputs
>    
>     | Name | Description |
>     |------|-------------|
>     | vpc_id | The VPC ID. |

We are looking to use this to document our terraform modules (multiple tf files)

`./terraform-docs-v0.4.5-darwin-amd64 md *.tf`

I was playing around attempting to put readme markdown (encasulated by '/\*\*' '\*\*/') into a readme.tf file for automatic inclusion.

_Seems that the **comment section** is only read from `main.tf`, is this by design?_

**Comment by metmajer** [comment]
Thanks for verifying, @jmcmaster05!

With regards to the comment section, putting the module comment into `main.tf` is currently a requirement. However, there's an ongoing discussion in #46 and I'd love you to share your thoughts on what @mvisonneau has proposed.
