### ISSUE TITLE
Add support for an XML renderer

### ISSUE THREAD

**Issue by metmajer** [segmentio/terraform-docs#77]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

We would like to add support for an additional XML renderer. If you are interested in making a contribution, please provide suggestions on the intended XML format here. The resulting pull request will need to contain an XML schema to support output validation.

**Comment by metmajer** [comment]
@jocgir

**Comment by russormes** [comment]
Hi there. Thanks for this project. Extracting the inputs and outputs into a table has made my life a little easier writing documentation. 

I wonder if there are any plans to support `.adoc` as an output, or to adopt a plugin pattern so more outputs can be supported?

**Comment by khos2ow** [comment]
I just created #149 as an interim ticket to track the plugin development. After release of `v0.8.0` I'm gonna add the support for `xml` and `yaml` and most probably attempt the plugin system in `v0.9.0`
