### ISSUE TITLE
Generate Section for locals

### ISSUE THREAD

**Issue by jmcmaster05** [segmentio/terraform-docs#80]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Sometimes devs decide to use `locals` instead of `variable` (usually for module input) and it would be nice to have that `locals section` automatically created by terraform-docs.

#### Actual Behavior

Generates only Inputs and Outputs.

```json
/**
 * This module has a variable and an output.  This text here will be output before any inputs or outputs!
 */

variable "subnet_ids" { 
  description = "a comma-separated list of subnet IDs"
} 

// The VPC ID.
output "vpc_id" { 
  value = "vpc-5c1f55fd"
} 

locals { 
  aws_region = "us-east-1"
} 
```

`terraform-docs md main.tf`

> This module has a variable and an output.  This text here will be output before any inputs or outputs!
> ## Inputs
> | Name | Description | Type | Default | Required |
> |------|-------------|:----:|:-----:|:-----:|
> | subnet_ids | a comma-separated list of subnet IDs | string | - | yes |
> ## Outputs
> 
> | Name | Description |
> |------|-------------|
> | vpc_id | The VPC ID. |

#### Expected Behavior

Hoping to see a locals section.

> This module has a variable and an output.  This text here will be output before any inputs or outputs!
> ## Inputs
> | Name | Description | Type | Default | Required |
> |------|-------------|:----:|:-----:|:-----:|
> | subnet_ids | a comma-separated list of subnet IDs | string | - | yes |
> ## Outputs
> | Name | Description |
> |------|-------------|
> | vpc_id | The VPC ID. |
> ## Locals
> | Name | Value |
> |------|-------------|
> | aws_region | us-east-1 |

### Version

You can get this information via `terraform-docs --version`.

Brew Installed Version

`terraform-docs --version`

> dev

Downloaded from [Releases](https://github.com/segmentio/terraform-docs/releases)

`./terraform-docs-v0.4.5-darwin-amd64 --version`

> 0.4.5

**Comment by metmajer** [comment]
@jmcmaster05 I am not at all sure if this is what we should do. After all, `locals` contain implementation details and are not part of the user-facing interface of a module. The art of proper encapsulation involves data hiding, which means giving the user access to certain information while abstracting away the internal details. By documenting the `locals`, we would violate this principle and this shouldn't be our goal with `terraform-docs`. In other words, if someone is interested in implementation details, they should go look up the implementation ;-)

**Comment by jmcmaster05** [comment]
I follow, show in `variable` or hide in `locals`.
