### ISSUE TITLE
Support handling of inputs provided via CLI

### ISSUE THREAD

**Issue by metmajer** [segmentio/terraform-docs#83]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

We want to integrate a clean handling of arbitrary data provided to the application through the CLI.

**Comment by metmajer** [comment]
Depends on #82.

**Comment by khos2ow** [comment]
This is not needed anymore after we migrated to Cobra #116
