### ISSUE TITLE
terraform-docs --version does not provide proper output

### ISSUE THREAD

**Issue by tbugfinder** [segmentio/terraform-docs#86]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Execution of `terraform-docs --version` on Linux only outputs `dev`.

#### Actual Behavior

Output:

```
]# terraform-docs --version
dev

```

Do you have long logs to share? Please go to https://ghostbin.com and insert the link here.

#### Expected Behavior

Expected output would be the applicable release.

```
v0.5.0
```

### Replication Case

Tell us which steps to take to replicate your problem.

1. go get -v github.com/segmentio/terraform-docs
2. terraform-docs --version

### Version

You can get this information via `terraform-docs --version`.
dev

**Comment by tbugfinder** [comment]
The execution of `cat` in Makefile is not supported on Windows. On Windows `type` would be used.
Depending on the version of `make` the file could be read by the `<` operator or by an if clause cat/type could be set.

see [link](https://stackoverflow.com/questions/6767413/create-a-variable-in-a-makefile-by-reading-contents-of-another-file)

```
FILE     := ./VERSION
VERSION :=$(file < $(FILE))
```

or 

```
cat := $(if $(filter $(OS),Windows_NT),type,cat)
VERSION := $(shell $(cat) ./VERSION)
```

**Comment by tbugfinder** [comment]
I reviewed again.
Binaries within the releases download support `--version`. If I download terraform-docs using `go get github.com/segmentio/terraform-docs`, `--version` just gives `dev`.
Looks like I was expecting to get latest release but I get latest build.

Do you know which go get command would download a specific version?

**Comment by metmajer** [comment]
Hi @tbugfinder. Thank you for your interest in this project!

`go get` merely fetches the repository's master branch and is not the right tool if you want to enforce a specific version. If you need control over your Golang packages' versions, then please have a look at [Golang's `dep` tool](https://github.com/golang/dep).

If you don't need the project's sources in your `GOPATH`, but all you need is a `terraform-docs` executable at a specific version, please have a look at the project's [releases](https://github.com/segmentio/terraform-docs/releases).

**Comment by tbugfinder** [comment]
A version output of just `dev` is very minimal even for a nightly master build. Would adding a build date to the version make sense? How would you deal with a bug report which refers to a version `dev`? When was this `dev` version built, is it really the latest `dev` build or is it `dev` version by 6 months ago?
