### ISSUE TITLE
Add support for controlling the indentation level of headers when rendering Markdown

### ISSUE THREAD

**Issue by metmajer** [segmentio/terraform-docs#89]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

We would like to have the possibility to use an option `--indent` to control the indentation level of Markdown headers produced by the Markdown renderer. Currently, headers such as `Inputs` and `Outputs` are statically prefixed with `##`, which means an indentation level of `2`(which should remain the default).

Why important? People make use of pre-commit hooks to automatically inject the `terraform-docs` generated documentation into their project's `README.md`. Since our document may be inserted at a lower level, have control over the indentation level of Markdown headers would create cleaner looking documents.

**Comment by metmajer** [comment]
Depends on #83.

**Comment by johncblandii** [comment]
I would love to see this one in there.
