### ISSUE TITLE
Wrong required field when `default` is an object

### ISSUE THREAD

**Issue by mthenw** [segmentio/terraform-docs#9]
Hey,

I have following variable defined 
```
variable "amis" {
  default = {
    "us-east-1" = "ami-8f7687e2"
    "us-west-1" = "ami-bb473cdb"
    "us-west-2" = "ami-84b44de4"
    "eu-west-1" = "ami-4e6ffe3d"
    "eu-central-1" = "ami-b0cc23df"
    "ap-northeast-1" = "ami-095dbf68"
    "ap-southeast-1" = "ami-cf03d2ac"
    "ap-southeast-2" = "ami-697a540a"
  }
}
```

`terraform-docs` thinks that this variable is required.

**Comment by yields** [comment]
Nice catch, i'm not sure what the correct thing to do here since the `"amis"` is a map, it is not usable by users of the module i think? so maybe it shouldn't show up at all?

willing to hear any ideas / suggestions.

**Comment by yields** [comment]
Pushed a fix, lmk how it looks and i can release.

**Comment by mthenw** [comment]
LGTM

I think it's useful that you can override that variable so it shouldn't be skipped. IMHO it should be treated the same way as other types. If there is a "default" defined it should not be marked as required.

**Comment by mthenw** [comment]
Hmm, one thing more. `<map>` is interpreted by markdown so it doesn't show at all in rendered .md :/

**Comment by yields** [comment]
great catch, fixed :)

**Comment by mthenw** [comment]
awesome, thanks!
