### ISSUE TITLE
Unify behavior of empty Default among different print types

### ISSUE THREAD

**Issue by khos2ow** [segmentio/terraform-docs#93]
### Prerequisites

Put an `x` into the box that applies:

- [x] This issue describes a bug.
- [ ] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Following up a discussion in #81 the behavior of _empty_ `Default` needs to be unified between different `print` types. Considering:

- `json`: technically can be remained as empty since empty JSON attributed is meaningful
- `markdown`
  - one of the following for `table`
    - `Default: -`
    - `Default: n/a`
    - `Default: ""`
    - `Default` cannot be hidden because some row of the table might still have values
  - one of the following for `document`
    - `Default: -`
    - `Default: n/a`
    - `Default: ""`
    - hide `Default` altogether
      - `Required Inputs`'s value can be hidden all the times
      - `Optional Inputs`'s value can be hidden as well for consistency.

**Comment by metmajer** [comment]
The interesting part of the discussion in #81 starts [here](https://github.com/segmentio/terraform-docs/pull/81#discussion_r234400342).
