### ISSUE TITLE
Terraform 0.12 support

### ISSUE THREAD

**Issue by querry43** [segmentio/terraform-docs#95]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

Terraform 0.12 allows for some new syntax.  I am working with 0.12 now so I can be ready for it when it's released.  It would be nice to generate documentation for it.

#### Actual Behavior

```
$ terraform-docs variables.tf
2018/12/10 07:19:36 At 3:10: Unknown token: 3:10 IDENT object
```
```
$ cat variables.tf
variable zone {
  description = "aws_route53_zone zone object in which to create records"
  type = object({
    id = string
  })
}

variable recordsets {
  description = "list of objects with name=string, type=string, ttl=number and records=list(string) fields"
  type = list(object({
    name    = string
    type    = string
    ttl     = number
    records = list(string)
  }))
}
```

#### Expected Behavior

terraform-docs can document terraform 0.12 modules.

### Replication Case

Tell us which steps to take to replicate your problem.

1. Create a terraform file with object types and/or unquoted variables.
2. run terraform-docs on it
3. wallow in disappointment

### Version

```dev```
(installed via `go get` 2018-12-10)

**Comment by metmajer** [comment]
Hi @querry43. Thank you for your interest in this project!

We already have Terraform 0.12 on our agenda, for which we have issue #62 open. I hence close this issue as a duplicate. Terraform 0.12 with HCL2 is currently *alpha* and still has to mature before we can offer a working integration. Don't be disappointed :-)
