### ISSUE TITLE
In-place update generated documents in file

### ISSUE THREAD

**Issue by khos2ow** [segmentio/terraform-docs#99]
### Prerequisites

Put an `x` into the box that applies:

- [ ] This issue describes a bug.
- [x] This issue describes a feature request.

For more information, see the [Contributing Guidelines](https://github.com/segmentio/terraform-docs/tree/master/CONTRIBUTING.md).

### Description

One of the main use-cases of `terraform-docs` as a tool is to generate Terraform configuration and update `README.md` file. I've managed to achieve this with a heavily hacked target in `Makefile` using sed and awk in conjunction of this tool to in-place update the content of README.

This is to open up discussion / brainstorming around the subject to see if it makes sense to include that as a built-in functionality of this tool. Something like `--update-file FILE` which adds following content:

```markdown
<!-- Terraform Document Begin -->
...
generated output of terraform-doc [json|markdown|md] ...
...
<!-- Terraform Document End -->
```

where:

- if `Begin` and `End` tokens don't exist in `FILE`, generates above snippet and appends it at the end of `FILE`
- if `Begin` and `End` tokens exist in `FILE`, replace the inner content between the tokens with newly generated document

### Version

You can get this information via `terraform-docs --version`.

**Comment by metmajer** [comment]
Hey @khos2ow! Here's an approach that I think is quite viable: [pre-commit](https://github.com/pre-commit/pre-commit) is a tool that allows you to install a number of Git pre-commit hooks into your project. These hooks get automatically triggered when you do a `git commit`. The hook you'll be interested in can be found in this repository: [antonbabenko/pre-commit-terraform](https://github.com/antonbabenko/pre-commit-terraform). Looking that the repository's [.pre-commit-config.yaml#L9-L16](https://github.com/antonbabenko/pre-commit-terraform/blob/master/.pre-commit-hooks.yaml#L9-L16) shows how you can pass random arguments to the `terraform-docs` binary. Hope this helps :)

**Comment by khos2ow** [comment]
Thank you @metmajer for the response and provided links, they are actually pretty cool. And sorry for my delayed response, I'm _technically_ on vacation! :wink: 

Anyways, although using `pre-commit` will be really cool, but I think it's mutually exclusive of what I'm proposing. Considering [terraform_docs.sh#L65-L73](https://github.com/antonbabenko/pre-commit-terraform/blob/master/terraform_docs.sh#L65-L73) it still depends on _external_ tool, `perl` in this case, which technically might not be available on one's workstation but `terraform-docs` is. And in reality those line can be replaced as

```
terraform-docs $args md --update-file "$text_file" ./ > "$tmp_file"
```

And besides, it requires installing pre-commit binary in all relevant workstations and pre-commit configs in all relevant repos, which might be slightly inconvenient, but at least way better of `sed` and `awk` I'm currently using!

**Comment by metmajer** [comment]
Hmm... are you talking about Linux or Windows machines? Practically speaking, `perl` has never been missing on the Linux machines I came across in the last decade or so.

I see what you want to propose, but I really don't see this in the scope of `terraform-docs`. If you do see a better approach than what's currently provided in [terraform_docs.sh#L65-L73](url
https://github.com/antonbabenko/pre-commit-terraform/blob/master/terraform_docs.sh#L65-L73), feel free to discuss an alternative solution there. I like to go with the UNIX philosophy: do one thing and do it well.

**Comment by khos2ow** [comment]
That's a reasonable argument, and in the meantime I've already incorporated the idea from `pre-commit` example into standalone `Makefile` target.

and +1 on Unix philosophy. I'm gonna close this issue.

**Comment by metmajer** [comment]
Thanks @khos2ow, greatly appreciate your input on improving this project!
